version: '3.9'

services:
  app:
    image: 'ruby'
    working_dir: /app
    volumes:
      - .:/app
      - rubygems:/usr/local/bundle
      - gemconfig:/root/.local/share/gem
    environment:
      REDIS_URL: redis://redis:6379/0
      
    ports:
      - "3000:3000"
    
  redis:
    image: redis
    
volumes:
  rubygems:
  gemconfig: