#!/bin/bash

docker run \
  --rm \
  --name rebase-labs \
  -w /app \
  -v $(pwd):/app \
  -v /rubygems:/usr/local/bundle \
  -enviroment: REDIS_URL: redis://redis:6379/0 \
  -p 3000:3000 \
  --network rebase-labs \
  ruby \
  bash -c " ruby server.rb"